name: DonkDemo
options:
  bundleIdPrefix: io.github.dimashbk
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
packages:
  Donk:
    path: ..
  GRPC:
    url: https://github.com/grpc/grpc-swift.git
    majorVersion: 1.21.0
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    from: 1.25.0
targets:
  DonkDemo:
    type: application
    platform: iOS
    sources:
      - path: DonkDemo
    dependencies:
      - package: Donk
        product: Donk
      - package: Donk
        product: DonkGRPC
      - package: GRPC
        product: GRPC
      - package: SwiftProtobuf
        product: SwiftProtobuf
    info:
      path: DonkDemo/Info.plist
      properties:
        CFBundleDisplayName: donk demo
        UILaunchScreen: {}
        CADisableMinimumFrameDurationOnPhone: true
        UIApplicationSupportsIndirectInputEvents: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes: [remote-notification]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.dimashbk.donkdemo
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
