//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: echo.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Donk_Echo_V1_EchoClient`, then call methods of this protocol to make API calls.
internal protocol Donk_Echo_V1_EchoClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? { get }

  func get(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>

  func expand(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions?,
    handler: @escaping (Donk_Echo_V1_EchoResponse) -> Void
  ) -> ServerStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>

  func collect(
    callOptions: CallOptions?
  ) -> ClientStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>

  func update(
    callOptions: CallOptions?,
    handler: @escaping (Donk_Echo_V1_EchoResponse) -> Void
  ) -> BidirectionalStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>
}

extension Donk_Echo_V1_EchoClientProtocol {
  internal var serviceName: String {
    return "donk.echo.v1.Echo"
  }

  /// Unary call to Get
  ///
  /// - Parameters:
  ///   - request: Request to send to Get.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeUnaryCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.get.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInterceptors() ?? []
    )
  }

  /// Server streaming call to Expand
  ///
  /// - Parameters:
  ///   - request: Request to send to Expand.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func expand(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Donk_Echo_V1_EchoResponse) -> Void
  ) -> ServerStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeServerStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.expand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExpandInterceptors() ?? [],
      handler: handler
    )
  }

  /// Client streaming call to Collect
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata, status and response.
  internal func collect(
    callOptions: CallOptions? = nil
  ) -> ClientStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeClientStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.collect.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCollectInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to Update
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func update(
    callOptions: CallOptions? = nil,
    handler: @escaping (Donk_Echo_V1_EchoResponse) -> Void
  ) -> BidirectionalStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeBidirectionalStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.update.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Donk_Echo_V1_EchoClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Donk_Echo_V1_EchoNIOClient")
internal final class Donk_Echo_V1_EchoClient: Donk_Echo_V1_EchoClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the donk.echo.v1.Echo service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Donk_Echo_V1_EchoNIOClient: Donk_Echo_V1_EchoClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol?

  /// Creates a client for the donk.echo.v1.Echo service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Donk_Echo_V1_EchoAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? { get }

  func makeGetCall(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>

  func makeExpandCall(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>

  func makeCollectCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncClientStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>

  func makeUpdateCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Donk_Echo_V1_EchoAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Donk_Echo_V1_EchoClientMetadata.serviceDescriptor
  }

  internal var interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeGetCall(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeAsyncUnaryCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.get.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInterceptors() ?? []
    )
  }

  internal func makeExpandCall(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeAsyncServerStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.expand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExpandInterceptors() ?? []
    )
  }

  internal func makeCollectCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncClientStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeAsyncClientStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.collect.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCollectInterceptors() ?? []
    )
  }

  internal func makeUpdateCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.update.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Donk_Echo_V1_EchoAsyncClientProtocol {
  internal func get(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Donk_Echo_V1_EchoResponse {
    return try await self.performAsyncUnaryCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.get.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetInterceptors() ?? []
    )
  }

  internal func expand(
    _ request: Donk_Echo_V1_EchoRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Donk_Echo_V1_EchoResponse> {
    return self.performAsyncServerStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.expand.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeExpandInterceptors() ?? []
    )
  }

  internal func collect<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) async throws -> Donk_Echo_V1_EchoResponse where RequestStream: Sequence, RequestStream.Element == Donk_Echo_V1_EchoRequest {
    return try await self.performAsyncClientStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.collect.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCollectInterceptors() ?? []
    )
  }

  internal func collect<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) async throws -> Donk_Echo_V1_EchoResponse where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Donk_Echo_V1_EchoRequest {
    return try await self.performAsyncClientStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.collect.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCollectInterceptors() ?? []
    )
  }

  internal func update<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Donk_Echo_V1_EchoResponse> where RequestStream: Sequence, RequestStream.Element == Donk_Echo_V1_EchoRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.update.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? []
    )
  }

  internal func update<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Donk_Echo_V1_EchoResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Donk_Echo_V1_EchoRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Donk_Echo_V1_EchoClientMetadata.Methods.update.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Donk_Echo_V1_EchoAsyncClient: Donk_Echo_V1_EchoAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Donk_Echo_V1_EchoClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Donk_Echo_V1_EchoClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'get'.
  func makeGetInterceptors() -> [ClientInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when invoking 'expand'.
  func makeExpandInterceptors() -> [ClientInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when invoking 'collect'.
  func makeCollectInterceptors() -> [ClientInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when invoking 'update'.
  func makeUpdateInterceptors() -> [ClientInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]
}

internal enum Donk_Echo_V1_EchoClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Echo",
    fullName: "donk.echo.v1.Echo",
    methods: [
      Donk_Echo_V1_EchoClientMetadata.Methods.get,
      Donk_Echo_V1_EchoClientMetadata.Methods.expand,
      Donk_Echo_V1_EchoClientMetadata.Methods.collect,
      Donk_Echo_V1_EchoClientMetadata.Methods.update,
    ]
  )

  internal enum Methods {
    internal static let get = GRPCMethodDescriptor(
      name: "Get",
      path: "/donk.echo.v1.Echo/Get",
      type: GRPCCallType.unary
    )

    internal static let expand = GRPCMethodDescriptor(
      name: "Expand",
      path: "/donk.echo.v1.Echo/Expand",
      type: GRPCCallType.serverStreaming
    )

    internal static let collect = GRPCMethodDescriptor(
      name: "Collect",
      path: "/donk.echo.v1.Echo/Collect",
      type: GRPCCallType.clientStreaming
    )

    internal static let update = GRPCMethodDescriptor(
      name: "Update",
      path: "/donk.echo.v1.Echo/Update",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Donk_Echo_V1_EchoProvider: CallHandlerProvider {
  var interceptors: Donk_Echo_V1_EchoServerInterceptorFactoryProtocol? { get }

  func get(request: Donk_Echo_V1_EchoRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Donk_Echo_V1_EchoResponse>

  func expand(request: Donk_Echo_V1_EchoRequest, context: StreamingResponseCallContext<Donk_Echo_V1_EchoResponse>) -> EventLoopFuture<GRPCStatus>

  func collect(context: UnaryResponseCallContext<Donk_Echo_V1_EchoResponse>) -> EventLoopFuture<(StreamEvent<Donk_Echo_V1_EchoRequest>) -> Void>

  func update(context: StreamingResponseCallContext<Donk_Echo_V1_EchoResponse>) -> EventLoopFuture<(StreamEvent<Donk_Echo_V1_EchoRequest>) -> Void>
}

extension Donk_Echo_V1_EchoProvider {
  internal var serviceName: Substring {
    return Donk_Echo_V1_EchoServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Get":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeGetInterceptors() ?? [],
        userFunction: self.get(request:context:)
      )

    case "Expand":
      return ServerStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeExpandInterceptors() ?? [],
        userFunction: self.expand(request:context:)
      )

    case "Collect":
      return ClientStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeCollectInterceptors() ?? [],
        observerFactory: self.collect(context:)
      )

    case "Update":
      return BidirectionalStreamingServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeUpdateInterceptors() ?? [],
        observerFactory: self.update(context:)
      )

    default:
      return nil
    }
  }
}

/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Donk_Echo_V1_EchoAsyncProvider: CallHandlerProvider, Sendable {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Donk_Echo_V1_EchoServerInterceptorFactoryProtocol? { get }

  func get(
    request: Donk_Echo_V1_EchoRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Donk_Echo_V1_EchoResponse

  func expand(
    request: Donk_Echo_V1_EchoRequest,
    responseStream: GRPCAsyncResponseStreamWriter<Donk_Echo_V1_EchoResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws

  func collect(
    requestStream: GRPCAsyncRequestStream<Donk_Echo_V1_EchoRequest>,
    context: GRPCAsyncServerCallContext
  ) async throws -> Donk_Echo_V1_EchoResponse

  func update(
    requestStream: GRPCAsyncRequestStream<Donk_Echo_V1_EchoRequest>,
    responseStream: GRPCAsyncResponseStreamWriter<Donk_Echo_V1_EchoResponse>,
    context: GRPCAsyncServerCallContext
  ) async throws
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Donk_Echo_V1_EchoAsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Donk_Echo_V1_EchoServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Donk_Echo_V1_EchoServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Donk_Echo_V1_EchoServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Get":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeGetInterceptors() ?? [],
        wrapping: { try await self.get(request: $0, context: $1) }
      )

    case "Expand":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeExpandInterceptors() ?? [],
        wrapping: { try await self.expand(request: $0, responseStream: $1, context: $2) }
      )

    case "Collect":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeCollectInterceptors() ?? [],
        wrapping: { try await self.collect(requestStream: $0, context: $1) }
      )

    case "Update":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Donk_Echo_V1_EchoRequest>(),
        responseSerializer: ProtobufSerializer<Donk_Echo_V1_EchoResponse>(),
        interceptors: self.interceptors?.makeUpdateInterceptors() ?? [],
        wrapping: { try await self.update(requestStream: $0, responseStream: $1, context: $2) }
      )

    default:
      return nil
    }
  }
}

internal protocol Donk_Echo_V1_EchoServerInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when handling 'get'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetInterceptors() -> [ServerInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when handling 'expand'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeExpandInterceptors() -> [ServerInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when handling 'collect'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCollectInterceptors() -> [ServerInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]

  /// - Returns: Interceptors to use when handling 'update'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateInterceptors() -> [ServerInterceptor<Donk_Echo_V1_EchoRequest, Donk_Echo_V1_EchoResponse>]
}

internal enum Donk_Echo_V1_EchoServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "Echo",
    fullName: "donk.echo.v1.Echo",
    methods: [
      Donk_Echo_V1_EchoServerMetadata.Methods.get,
      Donk_Echo_V1_EchoServerMetadata.Methods.expand,
      Donk_Echo_V1_EchoServerMetadata.Methods.collect,
      Donk_Echo_V1_EchoServerMetadata.Methods.update,
    ]
  )

  internal enum Methods {
    internal static let get = GRPCMethodDescriptor(
      name: "Get",
      path: "/donk.echo.v1.Echo/Get",
      type: GRPCCallType.unary
    )

    internal static let expand = GRPCMethodDescriptor(
      name: "Expand",
      path: "/donk.echo.v1.Echo/Expand",
      type: GRPCCallType.serverStreaming
    )

    internal static let collect = GRPCMethodDescriptor(
      name: "Collect",
      path: "/donk.echo.v1.Echo/Collect",
      type: GRPCCallType.clientStreaming
    )

    internal static let update = GRPCMethodDescriptor(
      name: "Update",
      path: "/donk.echo.v1.Echo/Update",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}
