//
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the protocol buffer compiler.
// Source: hello.proto
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Hello_HelloServiceClient`, then call methods of this protocol to make API calls.
internal protocol Hello_HelloServiceClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? { get }

  func sayHello(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Hello_HelloRequest, Hello_HelloResponse>

  func lotsOfReplies(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions?,
    handler: @escaping (Hello_HelloResponse) -> Void
  ) -> ServerStreamingCall<Hello_HelloRequest, Hello_HelloResponse>

  func lotsOfGreetings(
    callOptions: CallOptions?
  ) -> ClientStreamingCall<Hello_HelloRequest, Hello_HelloResponse>

  func bidiHello(
    callOptions: CallOptions?,
    handler: @escaping (Hello_HelloResponse) -> Void
  ) -> BidirectionalStreamingCall<Hello_HelloRequest, Hello_HelloResponse>
}

extension Hello_HelloServiceClientProtocol {
  internal var serviceName: String {
    return "hello.HelloService"
  }

  /// Unary call to SayHello
  ///
  /// - Parameters:
  ///   - request: Request to send to SayHello.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sayHello(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeUnaryCall(
      path: Hello_HelloServiceClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }

  /// Server streaming call to LotsOfReplies
  ///
  /// - Parameters:
  ///   - request: Request to send to LotsOfReplies.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func lotsOfReplies(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Hello_HelloResponse) -> Void
  ) -> ServerStreamingCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeServerStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfReplies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfRepliesInterceptors() ?? [],
      handler: handler
    )
  }

  /// Client streaming call to LotsOfGreetings
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata, status and response.
  internal func lotsOfGreetings(
    callOptions: CallOptions? = nil
  ) -> ClientStreamingCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeClientStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfGreetings.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfGreetingsInterceptors() ?? []
    )
  }

  /// Bidirectional streaming call to BidiHello
  ///
  /// Callers should use the `send` method on the returned object to send messages
  /// to the server. The caller should send an `.end` after the final message has been sent.
  ///
  /// - Parameters:
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ClientStreamingCall` with futures for the metadata and status.
  internal func bidiHello(
    callOptions: CallOptions? = nil,
    handler: @escaping (Hello_HelloResponse) -> Void
  ) -> BidirectionalStreamingCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeBidirectionalStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.bidiHello.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBidiHelloInterceptors() ?? [],
      handler: handler
    )
  }
}

@available(*, deprecated)
extension Hello_HelloServiceClient: @unchecked Sendable {}

@available(*, deprecated, renamed: "Hello_HelloServiceNIOClient")
internal final class Hello_HelloServiceClient: Hello_HelloServiceClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the hello.HelloService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Hello_HelloServiceNIOClient: Hello_HelloServiceClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol?

  /// Creates a client for the hello.HelloService service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Hello_HelloServiceAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? { get }

  func makeSayHelloCall(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Hello_HelloRequest, Hello_HelloResponse>

  func makeLotsOfRepliesCall(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncServerStreamingCall<Hello_HelloRequest, Hello_HelloResponse>

  func makeLotsOfGreetingsCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncClientStreamingCall<Hello_HelloRequest, Hello_HelloResponse>

  func makeBidiHelloCall(
    callOptions: CallOptions?
  ) -> GRPCAsyncBidirectionalStreamingCall<Hello_HelloRequest, Hello_HelloResponse>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Hello_HelloServiceAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Hello_HelloServiceClientMetadata.serviceDescriptor
  }

  internal var interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeSayHelloCall(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeAsyncUnaryCall(
      path: Hello_HelloServiceClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }

  internal func makeLotsOfRepliesCall(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncServerStreamingCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeAsyncServerStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfReplies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfRepliesInterceptors() ?? []
    )
  }

  internal func makeLotsOfGreetingsCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncClientStreamingCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeAsyncClientStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfGreetings.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfGreetingsInterceptors() ?? []
    )
  }

  internal func makeBidiHelloCall(
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncBidirectionalStreamingCall<Hello_HelloRequest, Hello_HelloResponse> {
    return self.makeAsyncBidirectionalStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.bidiHello.path,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBidiHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Hello_HelloServiceAsyncClientProtocol {
  internal func sayHello(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Hello_HelloResponse {
    return try await self.performAsyncUnaryCall(
      path: Hello_HelloServiceClientMetadata.Methods.sayHello.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSayHelloInterceptors() ?? []
    )
  }

  internal func lotsOfReplies(
    _ request: Hello_HelloRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Hello_HelloResponse> {
    return self.performAsyncServerStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfReplies.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfRepliesInterceptors() ?? []
    )
  }

  internal func lotsOfGreetings<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) async throws -> Hello_HelloResponse where RequestStream: Sequence, RequestStream.Element == Hello_HelloRequest {
    return try await self.performAsyncClientStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfGreetings.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfGreetingsInterceptors() ?? []
    )
  }

  internal func lotsOfGreetings<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) async throws -> Hello_HelloResponse where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Hello_HelloRequest {
    return try await self.performAsyncClientStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.lotsOfGreetings.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLotsOfGreetingsInterceptors() ?? []
    )
  }

  internal func bidiHello<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Hello_HelloResponse> where RequestStream: Sequence, RequestStream.Element == Hello_HelloRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.bidiHello.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBidiHelloInterceptors() ?? []
    )
  }

  internal func bidiHello<RequestStream>(
    _ requests: RequestStream,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncResponseStream<Hello_HelloResponse> where RequestStream: AsyncSequence & Sendable, RequestStream.Element == Hello_HelloRequest {
    return self.performAsyncBidirectionalStreamingCall(
      path: Hello_HelloServiceClientMetadata.Methods.bidiHello.path,
      requests: requests,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeBidiHelloInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Hello_HelloServiceAsyncClient: Hello_HelloServiceAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Hello_HelloServiceClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

internal protocol Hello_HelloServiceClientInterceptorFactoryProtocol: Sendable {

  /// - Returns: Interceptors to use when invoking 'sayHello'.
  func makeSayHelloInterceptors() -> [ClientInterceptor<Hello_HelloRequest, Hello_HelloResponse>]

  /// - Returns: Interceptors to use when invoking 'lotsOfReplies'.
  func makeLotsOfRepliesInterceptors() -> [ClientInterceptor<Hello_HelloRequest, Hello_HelloResponse>]

  /// - Returns: Interceptors to use when invoking 'lotsOfGreetings'.
  func makeLotsOfGreetingsInterceptors() -> [ClientInterceptor<Hello_HelloRequest, Hello_HelloResponse>]

  /// - Returns: Interceptors to use when invoking 'bidiHello'.
  func makeBidiHelloInterceptors() -> [ClientInterceptor<Hello_HelloRequest, Hello_HelloResponse>]
}

internal enum Hello_HelloServiceClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "HelloService",
    fullName: "hello.HelloService",
    methods: [
      Hello_HelloServiceClientMetadata.Methods.sayHello,
      Hello_HelloServiceClientMetadata.Methods.lotsOfReplies,
      Hello_HelloServiceClientMetadata.Methods.lotsOfGreetings,
      Hello_HelloServiceClientMetadata.Methods.bidiHello,
    ]
  )

  internal enum Methods {
    internal static let sayHello = GRPCMethodDescriptor(
      name: "SayHello",
      path: "/hello.HelloService/SayHello",
      type: GRPCCallType.unary
    )

    internal static let lotsOfReplies = GRPCMethodDescriptor(
      name: "LotsOfReplies",
      path: "/hello.HelloService/LotsOfReplies",
      type: GRPCCallType.serverStreaming
    )

    internal static let lotsOfGreetings = GRPCMethodDescriptor(
      name: "LotsOfGreetings",
      path: "/hello.HelloService/LotsOfGreetings",
      type: GRPCCallType.clientStreaming
    )

    internal static let bidiHello = GRPCMethodDescriptor(
      name: "BidiHello",
      path: "/hello.HelloService/BidiHello",
      type: GRPCCallType.bidirectionalStreaming
    )
  }
}

